name: Habit Tracker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y software-properties-common make cmake git

        # Install GCC 14
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt update
        sudo apt install -y g++-14
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100

        # Build FTXUI
        git clone --recursive https://github.com/ArthurSonzogni/FTXUI.git
        cd FTXUI
        cmake -B build -S .
        cmake --build build
        sudo cmake --install build
        cd ..

    - name: Build Habit Tracker
      run: make
